language: ruby
rvm:
- 2.2
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_f0453a157e60_key -iv $encrypted_f0453a157e60_iv
  -in travis_id_rsa.enc -out ../travis_id_rsa -d
- git config --global user.name "Travis CI User"
- git config --global user.email "travis@build_${TRAVIS_BUILD_NUMBER}"
- git config --global push.default simple
- git clone git@github.com:${TRAVIS_REPO_SLUG}.git ${build_dir}
- git checkout ${source_branch}
- "(cd ${build_dir} ; git checkout ${destination_branch})"
- if [ $nojekyll = 'true' ]; then \ (cd ${build_dir} ; find . -maxdepth 1 -not -name
  .git -not -name . -exec rm --recursive --force {} \;) ;\ (cd ${build_dir} ; touch
  .nojekyll) ;\ fi
- gem update --system
before_script:
- bundle exec jekyll doctor
after_success:
- if [ $nojekyll = 'true' ]; then \ (cp --recursive _site/* ${build_dir}) ;\ else
  \ (ch ${build_dir} ; git merge ${source_branch}) ;\ fi
- cd ${build_dir}
- git add --all .
- git commit -m "Updating to ${TRAVIS_REPO_SLUG}@$(git log -1 --pretty=%h)"
- git push --quiet origin ${destination_branch}
env:
  global:
  - source_branch=master
  - destination_branch=gh-pages
  - build_dir='../_build'
  - nojekyll=false
