language: ruby
rvm:
- 2.2.0
# Whitelist branches
branches:
  only:
  - master
  exclude:
  - gh-pages
before_install:
# Decrypt ssh key. Automaticly added from 'travis encrypt-file id_rsa --add'
- openssl aes-256-cbc -K $encrypted_f0453a157e60_key -iv $encrypted_f0453a157e60_iv
  -in _secrets/id_rsa.enc -out ~/.ssh/id_rsa -d
# Set proper permissions for ssh key
- chmod 400 ~/.ssh/id_rsa
# Git settings
- git config --global user.name "Travis CI User"
- git config --global user.email "travis@build_${TRAVIS_BUILD_NUMBER}"
- git config --global push.default simple
- git clone git@github.com:${TRAVIS_REPO_SLUG}.git ${build_dir}
# Checkout to necassary branches
- git checkout ${source_branch}
- (cd ${build_dir} ;
  git show-ref --verify --quiet refs/heads/#{publish_branch} || git checkout -B ${publish_branch} ;
  git checkout ${publish_branch})
# Clear branch if not using Github Pages to render
- if [ $nojekyll = 'true' ]; then
    (cd ${build_dir} ; find . -maxdepth 1 -not -name .git -not -name . -exec rm --recursive --force {} \;) ;
    (cd ${build_dir} ; touch .nojekyll) ;
  fi
# Update gem
- gem update --system
# install: bundle install --jobs=3 --retry=3
before_script:
# jekyll configuration lint test
- bundle exec jekyll doctor
# script: bundle exec rake
after_success:
# Updated published branch
- if [ $nojekyll = 'true' ]; then
    (cp --recursive _site/* ${build_dir}) ;
  else
    (ch ${build_dir} ; git merge ${source_branch}) ;
  fi
- cd ${build_dir}
- git add --all .
- git commit -m "Updating to ${TRAVIS_REPO_SLUG}@$(git log -1 --pretty=%h)"
- git push --quiet origin ${publish_branch}
env:
  global:
  - source_branch=master
  - publish_branch=gh-pages
  # Temparary working directory
  - build_dir='../_build'
  # nojekyll will publish the post processed site
  - nojekyll=false
