language: ruby
rvm:
- 2.2.0
# Whitelist branches
branches:
  only:
  - master
  exclude:
  - gh-pages
before_install:
# Decrypt ssh key. Automaticly added from 'travis encrypt-file id_rsa --add'
- openssl aes-256-cbc -K $encrypted_f0453a157e60_key -iv $encrypted_f0453a157e60_iv
  -in _secrets/id_rsa.enc -out ~/.ssh/id_rsa -d
# Set proper permissions for ssh key
- chmod 400 ~/.ssh/id_rsa
# Git settings
- git config --global user.name "Travis CI User"
- git config --global user.email "travis@build_${TRAVIS_BUILD_NUMBER}"
- git config --global push.default simple
# Ensuring in correct branch
- git checkout ${source_branch}
# Update gem
- gem update --system
# install: bundle install --jobs=3 --retry=3
before_script:
# jekyll configuration lint test
- bundle exec jekyll doctor
# script: bundle exec rake
after_success:
# Clone using ssh
- git clone git@github.com:${TRAVIS_REPO_SLUG}.git ${build_dir}
- cd ${build_dir}
- git checkout -B ${publish_branch}
# Updated published branch
- if [ $nojekyll = 'true' ]; then
    find . -maxdepth 1 -not -name .git -not -name . -exec rm --recursive --force {} \; ;
    touch .nojekyll ;
    (cd - ; cp --recursive _site/* ${build_dir}) ;
  else
    git merge ${source_branch}) ;
  fi
- git add --all .
- git commit -m "Updating to ${TRAVIS_REPO_SLUG}@$(git log -1 --pretty=%h)"
- git push origin ${publish_branch}
env:
  global:
  - source_branch=master
  - publish_branch=gh-pages
  - build_dir='/tmp/jekyll_build'
  # nojekyll will publish the post processed site
  - nojekyll=false
