# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

timezone: America/Los_Angeles
encoding: utf-8

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
kramdown:
  input: GFM
  hard_wrap: false
sass:
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - _rake
  - LICENSE
  - README.md
  - id_rsa.enc

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# Native Github Pages will override
markdown: kramdown
lsi: false
safe: true
# source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
